### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by YoSuboDeToh** [LuckPerms/LuckPermsPlaceholders#14]
forge-1.12.2-14.23.5.2847-universal.jar
spongeforge-1.12.2-2838-7.1.8-RC3961.jar
LuckPerms-Sponge-5.0.9.jar
LuckHolders-1.0.0-SNAPSHOT.jar

https://pastebin.com/VkRBJAY0

**Comment by lucko** [comment]
Luckholders isn't actually my plugin, buuuut....

Follow the instructions here: https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility :)
