### ISSUE TITLE
%luckperms_expiry_time_<permission>% not working

### ISSUE THREAD

**Issue by rosiejane** [LuckPerms/LuckPermsPlaceholders#18]
Ever since i updated to 1.16.1 expiry time placeholders are not working

![image](https://user-images.githubusercontent.com/54243352/88815693-86d9e700-d1b3-11ea-9cf0-c0f9b36fdedd.png)

In 1.15.2 it worked fine look.

![image](https://user-images.githubusercontent.com/54243352/88815661-7e81ac00-d1b3-11ea-952c-b02080302eaf.png)

As you can see, 1.16.1 does not work
![image](https://user-images.githubusercontent.com/54243352/88816083-efc15f00-d1b3-11ea-83dd-f588fcdf387c.png)

Any ideas?

**Comment by rosiejane** [comment]
Still there has been no reply 2 weeks later. Hello???

**Comment by lucko** [comment]
This is a placeholder api issue as far as I know.

**Comment by Andre601** [comment]
Hey.

I would like to know, how LuckPermsPlaceholders handles PlaceholderAPI placeholders, as I really doubt that this is something caused on the end of PlaceholderAPI...

I just would like to point out, that something simple as changing the Server version should not have an impact on PlaceholderAPI. Please check the console for any startup errors and also provide the requested information as described in https://github.com/PlaceholderAPI/PlaceholderAPI/issues/449 earlier (Mainly the output of `/papi dump`)

**Comment by rosiejane** [comment]
Thank you for taking the time to reply to to this post also.

**Comment by rosiejane** [comment]
Please can you take a look at this @lucko

**Comment by lucko** [comment]
LuckPerms uses `me.clip.placeholderapi.util.TimeUtil ` to format times.

https://github.com/LuckPerms/LuckPermsPlaceholders/blob/5c73fadd10ef4163711cc74fcbb5bcb9cc36c2ab/luckperms-papi-expansion/src/main/java/me/lucko/luckperms/placeholders/LuckPermsExpansion.java#L71-L74

I haven't touched this code - there is no reason why it should work on 1.15 but not on 1.16 after updating PlaceholderAPI.

Please check your console to see if there are any error messages printed there.

**Comment by Andre601** [comment]
Does LP perhaps use outdated methods?
The more recent versions of PlaceholderAPI deprecated a few methods which no longer return sufficient information and instead print warnings or similar in the console. Could you @lucko double check that there aren't any methods used that are outdated?

**Comment by rosiejane** [comment]
Can i just share some more information. Every single placeholder on my server from every plugin has updated and is working perfectly since we update to 1.16.1. 

It is only the expiry time placeholders from luck p[erms that have not updated and are not working.

**Comment by rosiejane** [comment]
@Andre601 @lucko 

Do you have any more information on this please.

Andre601 i also canntog et the formatter working.

Lucko Does LP perhaps use outdated methods?

**Comment by rosiejane** [comment]
Hello? This issue needs to be reopened please.

@Andre601 
@lucko

**Comment by rosiejane** [comment]
Hello. I still cannot get this working. I have installed both the latest version of Luck Perms and Placeholder api and the expansion.

Time remaining still is not being displayed.

%luckperms_expiry_time_worldguard.region.bypass.survival.__global__.fly%

If anyone has got the time remaining placeholder working please can you paste me your code so i can try it please?

Thank you

@lucko 
@Andre601
